create table if not exists ticket (
    id varchar(64) primary key,
    requester_id varchar(128) not null,
    title varchar(255) not null,
    description varchar(2000) not null,
    status varchar(32) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists ticket_message (
    id bigint generated by default as identity primary key,
    ticket_id varchar(64) not null,
    sender_type varchar(32) not null,
    content varchar(4000) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists sop_document (
    id varchar(64) primary key,
    title varchar(255) not null,
    source varchar(255) not null,
    content varchar(4000) not null
);

create table if not exists agent_trace (
    id bigint generated by default as identity primary key,
    ticket_id varchar(64) not null,
    step_order integer not null,
    step varchar(64) not null,
    detail varchar(2000) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists tool_call_log (
    id bigint generated by default as identity primary key,
    ticket_id varchar(64) not null,
    tool_order integer not null,
    tool_name varchar(128) not null,
    arguments_json varchar(2000) not null,
    result_summary varchar(1000) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists pending_action (
    id bigint generated by default as identity primary key,
    ticket_id varchar(64) not null,
    action_order integer not null,
    action_type varchar(64) not null,
    summary varchar(1000) not null,
    status varchar(32) not null default 'PENDING',
    created_at timestamp not null default current_timestamp
);

create table if not exists mock_user_account (
    user_id varchar(128) primary key,
    account_status varchar(32) not null,
    display_name varchar(128)
);

create table if not exists mock_user_permission (
    id bigint generated by default as identity primary key,
    user_id varchar(128) not null,
    app_code varchar(64) not null,
    permission_code varchar(128) not null
);
